{% set name = "fastcache" %}
{% set version = "1.1.0" %}
{% set sha256 = "9a5c518b4c8b48c7f0e11f7d721bcabd0153bf7df17b167532afbf38ddd6c4be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbrady/fastcache/archive/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fastcache
    - fastcache._lrucache

  commands:
    - python -c "import fastcache; fastcache.test()"

  requires:
    - pytest

about:
  home: https://github.com/pbrady/fastcache
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'C implementation of Python 3 lru_cache'
  dev_url: https://github.com/pbrady/fastcache

extra:
  recipe-maintainers:
    - synapticarbors
